[package]
name = "pythontorust"
description = "You need to have a decent knowledge of both languages to use this program"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
